In [5]:
import pandas as pd
from datetime import datetime

from funciones.calculo_balance_demanda import *

In [6]:
hoy = datetime.now() 

inicio = "2020-01-01"
fin = hoy.strftime("%Y-%m-%d")

print(hoy)
print(inicio)
print(fin)

zonas = ["nacional", "peninsular", "ceuta", "melilla", "canarias", "baleares"]

2025-02-20 00:59:35.325635
2020-01-01
2025-02-20

## CALCULOS BALANCE Y DEMANDA ENERGETICA

#### Segun los parámetros que pasemos a las funciones podremos obtener un dataframe con el demanda y/o la balance energéticos para zona e intervalo de tiempo determinados, agrupado por días.

---

### CÁLCULO BALANCE ENERGÉTICO:

Generación (todas las tecnologías)+ Saldo almacenamiento + Saldo intercambios internacionales

In [7]:
balance_energetico_total(inicio, fin, "nacional")

            total_balance_nacional_(MWh)
fecha
2020-01-01                    574776.720
2020-01-02                    723522.375
2020-01-03                    754645.342
2020-01-04                    702390.878
2020-01-05                    651967.486
...                                  ...
2025-02-15                    651705.219
2025-02-16                    599087.640
2025-02-17                    703417.661
2025-02-18                    729142.540
2025-02-19                    697432.332

[1877 rows x 1 columns]

---

### CÁLCULO DEMANDA ENERGÉTICA:

Generación (todas las tecnologías) + pérdidas de transporte + Saldo Intercambios Internacionales (positivo o negativo)

In [8]:
demanda_energetica_total(inicio, fin, "nacional")

,total_generacion_nacional_(MWh),total_perdidas_transporte_nacional_(MWh),total_intercambios_nacional_(MWh),demanda_total_nacional_(MWh)
fecha,,,,
2020-01-01,586833.966,11036.029,984.272,598854.267
2020-01-02,692396.215,14634.267,26627.734,733658.216
2020-01-03,672539.279,14195.004,79819.793,766554.076
2020-01-04,667286.368,13140.725,51474.830,731901.923
2020-01-05,602982.974,11599.410,63066.799,677649.183
...,...,...,...,...
2025-02-15,713989.819,NaN,0.000,713989.819
2025-02-16,683044.940,NaN,0.000,683044.940
2025-02-17,743407.961,NaN,0.000,743407.961
2025-02-18,755656.740,NaN,-2752.000,752904.740
2025-02-19,674466.932,NaN,-3412.000,671054.932